fix msvc build
needed to include timezoneapi.h because:

/opt/msvc/kits/10/include/10.0.26100.0/um/minidumpapiset.h(626): error C3646: 'TimeZone': unknown override specifier
/opt/msvc/kits/10/include/10.0.26100.0/um/minidumpapiset.h(626): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int

yeah windows headers are cool